services:
  portainer:
    image: ${PORTAINER_IMAGE:-portainer/portainer-ce:latest}
    container_name: portainer
    network_mode: ${NETWORK_MODE:-container:tailscale}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      AGENT_SECRET: ${AGENT_SECRET}

volumes:
  portainer_data:
    external: true
